import React from "react";
import Link from "next/link";
import { AlertTriangle, ChevronLeft, Info, Brain, Activity, Target } from "lucide-react";
import "../globals.css";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#f7f3eb] text-[#1a1a1a] font-sans">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <Link href="/" className="inline-flex items-center text-teal-600 hover:text-teal-700 font-medium mb-12 transition-colors">
          <ChevronLeft className="w-4 h-4 mr-1" /> Back to Home
        </Link>

        <header className="mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-6 font-syne">About CortexFlow</h1>
          <p className="text-lg text-gray-600 leading-relaxed max-w-3xl">
            CortexFlow is a screening and exploration system engineered to demonstrate how cognitive analysis workflows can be built responsibly using modern speech-to-text models and deterministic linguistic analysis.
          </p>
        </header>

        {/* STRICT LEGAL DISCLAIMER */}
        <section className="mb-16">
          <div className="bg-red-50 border-l-4 border-red-500 p-6 rounded-r-2xl shadow-sm">
            <div className="flex items-start">
              <div className="flex-shrink-0">
                <AlertTriangle className="h-6 w-6 text-red-600" aria-hidden="true" />
              </div>
              <div className="ml-4">
                <h3 className="text-lg font-bold text-red-800 uppercase tracking-wide">Strict Non-Diagnostic Disclaimer</h3>
                <div className="mt-3 text-red-700 text-sm md:text-base leading-relaxed space-y-3 font-medium">
                  <p>
                    CortexFlow is strictly a demonstration and screening exploration system. <strong>It is NOT a medical device, NOT a diagnostic tool, and MUST NOT be used for clinical diagnosis, treatment planning, or medical advice.</strong>
                  </p>
                  <p>
                    The cognitive metrics, longitudinal trends, and neural circuit mappings generated by this platform are experimental indicators based on linguistic and prosodic algorithms. They do not constitute a medical evaluation.
                  </p>
                  <p>
                    If you or a loved one are experiencing cognitive decline, memory issues, or any medical concerns, please consult a qualified healthcare professional, neurologist, or licensed medical provider immediately.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Platform Capabilities */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-6 flex items-center font-syne">
            <Target className="w-6 h-6 mr-3 text-teal-500" /> Platform Capabilities
          </h2>
          <div className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
            <p className="text-gray-600 leading-relaxed mb-6">
              CortexFlow analyzes speech and text inputs to extract structured, actionable data across five primary cognitive domains. Our platform is designed to provide rapid screening workflows by combining:
            </p>
            <ul className="space-y-4 text-gray-700">
              <li className="flex items-start">
                <div className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-2 mr-3 flex-shrink-0" />
                <span><strong>Real-Time Processing:</strong> Direct browser-based voice capture and streaming transcripts.</span>
              </li>
              <li className="flex items-start">
                <div className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-2 mr-3 flex-shrink-0" />
                <span><strong>AI-Powered Transcription:</strong> Utilizing robust Gemini APIs for accurate speech-to-text conversion.</span>
              </li>
              <li className="flex items-start">
                <div className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-2 mr-3 flex-shrink-0" />
                <span><strong>Deterministic Feature Extraction:</strong> Ensuring mathematical transparency over black-box AI scores.</span>
              </li>
              <li className="flex items-start">
                <div className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-2 mr-3 flex-shrink-0" />
                <span><strong>Neural Mapping:</strong> Abstract metrics are visualized inside an interactive 3D brain workspace mapped to MNI152 coordinates.</span>
              </li>
            </ul>
          </div>
        </section>

        {/* Mathematical Models */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-6 flex items-center font-syne">
            <Activity className="w-6 h-6 mr-3 text-teal-500" /> Mathematical Models & Metrics
          </h2>
          <div className="prose prose-teal max-w-none text-gray-600 leading-relaxed space-y-6">
            <p>
              To avoid the pitfalls of opaque "AI scoring," CortexFlow relies on transparent, deterministic mathematical functions to evaluate the transcript. The system calculates deviations from standardized baselines across five neural regions.
            </p>

            <div className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm mt-8">
              <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
                <Brain className="w-5 h-5 mr-2 text-blue-500" /> 1. Lexical Domain (Broca's Area)
              </h3>
              <p className="mb-4 text-sm">Measures vocabulary richness and word retrieval capabilities.</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Type-Token Ratio (TTR):</strong> <code className="bg-gray-50 px-1 rounded text-teal-600">Unique Words / Total Words</code>. Measures lexical variation. A severe drop indicates word-finding difficulty.</li>
                <li><strong>Lexical Density:</strong> <code className="bg-gray-50 px-1 rounded text-teal-600">Content Words / Total Words</code>. Content words exclude grammatical stop-words.</li>
                <li><strong>Filler Rate:</strong> The frequency of hesitation markers (e.g., "um," "uh," "like") normalized per 100 words.</li>
              </ul>
            </div>

            <div className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
                <Brain className="w-5 h-5 mr-2 text-purple-500" /> 2. Semantic Domain (Wernicke's Area)
              </h3>
              <p className="mb-4 text-sm">Evaluates logical flow, comprehension, and tangential speech.</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Coherence Index:</strong> Uses <code className="bg-gray-50 px-1 rounded text-teal-600">Jaccard Similarity</code> across adjacent sentence vectors to measure topic adherence.</li>
                <li><strong>Idea Density:</strong> Average number of core conceptual words per utterance.</li>
                <li><strong>Tangentiality Scaling:</strong> An inverse mathematical function applied to the Coherence Index to quantify topic-wandering.</li>
              </ul>
            </div>

            <div className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
                <Brain className="w-5 h-5 mr-2 text-orange-500" /> 3. Prosody Domain (SMA)
              </h3>
              <p className="mb-4 text-sm">Analyzes the physical timing and rhythm of speech.</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Speech Rate:</strong> <code className="bg-gray-50 px-1 rounded text-teal-600">Total Words / Duration (minutes)</code>. A standard baseline is ~140 WPM.</li>
                <li><strong>Pause Frequency:</strong> The number of audio pauses (or heavy punctuation clusters) normalized per minute of speech.</li>
                <li><strong>Hesitation Ratio:</strong> The percentage of pauses exceeding 0.8 seconds relative to total pauses.</li>
              </ul>
            </div>

            <div className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
                <Brain className="w-5 h-5 mr-2 text-teal-500" /> 4. Syntax Domain (DLPFC)
              </h3>
              <p className="mb-4 text-sm">Measures grammatical complexity and executive function in speech planning.</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Mean Length of Utterance (MLU):</strong> <code className="bg-gray-50 px-1 rounded text-teal-600">Total Words / Sentence Count</code>.</li>
                <li><strong>Clause Depth Index:</strong> A weighted sum of subordinators (e.g., "because," "although") and mid-sentence phrasal breaks.</li>
                <li><strong>Passive Voice Ratio:</strong> Pattern matching for auxiliary verbs coupled with past participles, normalized by sentence count.</li>
              </ul>
            </div>

            <div className="bg-white rounded-xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
                <Brain className="w-5 h-5 mr-2 text-red-500" /> 5. Affective Domain (Amygdala)
              </h3>
              <p className="mb-4 text-sm">Quantifies emotional resonance and certainty within the speech sample.</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Sentiment Valence:</strong> <code className="bg-gray-50 px-1 rounded text-teal-600">(Positive Words - Negative Words) / (Positive + Negative + 1)</code>, scaled to a 0.0 - 1.0 index.</li>
                <li><strong>Arousal Rate:</strong> Frequency of high-intensity emotional markers.</li>
                <li><strong>Certainty Index:</strong> An inverse calculation of linguistic hedge words (e.g., "maybe," "perhaps," "guess").</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Footer / Contact */}
        <section className="border-t border-gray-200 pt-12 pb-8 flex flex-col items-center text-center">
          <Info className="w-8 h-8 text-gray-400 mb-4" />
          <h2 className="text-xl font-bold mb-4 font-syne">Have Questions?</h2>
          <p className="text-gray-500 mb-6 max-w-lg">
            For inquiries regarding the mathematical models, API access, or engineering details, please reach out to the development team.
          </p>
          <a 
            href="mailto:contact.manikaditya@gmail.com" 
            className="bg-teal-500 hover:bg-teal-600 text-white font-semibold py-3 px-8 rounded-full shadow-md transition-transform hover:-translate-y-0.5"
          >
            contact.manikaditya@gmail.com
          </a>
        </section>
      </div>
    </div>
  );
}
